-- 코드를 입력하세요
SELECT TB1.REST_ID
     , TB1.REST_NAME
     , TB1.FOOD_TYPE
     , TB1.FAVORITES
     , TB1.ADDRESS
     , TB2.REVIEW_SCORE AS SCORE
  FROM REST_INFO TB1
  LEFT JOIN (SELECT REST_ID
                  , ROUND(AVG(REVIEW_SCORE), 2) AS REVIEW_SCORE
               FROM REST_REVIEW
              GROUP BY REST_ID) TB2
    ON TB1.REST_ID = TB2.REST_ID
 WHERE TB1.ADDRESS LIKE '서울%'
   AND TB2.REVIEW_SCORE IS NOT NULL
 ORDER BY TB2.REVIEW_SCORE DESC, TB1.FAVORITES DESC;