-- 코드를 입력하세요
SELECT TB1.FLAVOR AS FLAVOR
  FROM FIRST_HALF TB1
  LEFT JOIN ICECREAM_INFO TB2
    ON TB1.FLAVOR = TB2.FLAVOR
 WHERE TB1.TOTAL_ORDER > 3000
   AND TB2.INGREDIENT_TYPE = 'fruit_based'
 ORDER BY TB1.TOTAL_ORDER DESC;